/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as SigninImport } from './routes/signin'
import { Route as IndexImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app/_route'
import { Route as AppRouteIndexImport } from './routes/app/_route.index'
import { Route as AppRouteShoppingImport } from './routes/app/_route.shopping'
import { Route as AppRouteRecipesImport } from './routes/app/_route.recipes'
import { Route as AppRouteIngredientsImport } from './routes/app/_route.ingredients'
import { Route as AppRouteRecipesAddImport } from './routes/app/_route.recipes.add'
import { Route as AppRouteIngredientsAddImport } from './routes/app/_route.ingredients.add'
import { Route as AppRouteRecipesPreviewIdImport } from './routes/app/_route.recipes.preview.$id'
import { Route as AppRouteRecipesEditIdImport } from './routes/app/_route.recipes.edit.$id'
import { Route as AppRouteIngredientsEditIdImport } from './routes/app/_route.ingredients.edit.$id'

// Create Virtual Routes

const AppImport = createFileRoute('/app')()

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const SigninRoute = SigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppRouteRoute = AppRouteImport.update({
  id: '/_route',
  getParentRoute: () => AppRoute,
} as any)

const AppRouteIndexRoute = AppRouteIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppRouteShoppingRoute = AppRouteShoppingImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppRouteRecipesRoute = AppRouteRecipesImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppRouteIngredientsRoute = AppRouteIngredientsImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppRouteRecipesAddRoute = AppRouteRecipesAddImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppRouteRecipesRoute,
} as any)

const AppRouteIngredientsAddRoute = AppRouteIngredientsAddImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppRouteIngredientsRoute,
} as any)

const AppRouteRecipesPreviewIdRoute = AppRouteRecipesPreviewIdImport.update({
  id: '/preview/$id',
  path: '/preview/$id',
  getParentRoute: () => AppRouteRecipesRoute,
} as any)

const AppRouteRecipesEditIdRoute = AppRouteRecipesEditIdImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AppRouteRecipesRoute,
} as any)

const AppRouteIngredientsEditIdRoute = AppRouteIngredientsEditIdImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AppRouteIngredientsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/app/_route': {
      id: '/app/_route'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/_route/ingredients': {
      id: '/app/_route/ingredients'
      path: '/ingredients'
      fullPath: '/app/ingredients'
      preLoaderRoute: typeof AppRouteIngredientsImport
      parentRoute: typeof AppRouteImport
    }
    '/app/_route/recipes': {
      id: '/app/_route/recipes'
      path: '/recipes'
      fullPath: '/app/recipes'
      preLoaderRoute: typeof AppRouteRecipesImport
      parentRoute: typeof AppRouteImport
    }
    '/app/_route/shopping': {
      id: '/app/_route/shopping'
      path: '/shopping'
      fullPath: '/app/shopping'
      preLoaderRoute: typeof AppRouteShoppingImport
      parentRoute: typeof AppRouteImport
    }
    '/app/_route/': {
      id: '/app/_route/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppRouteIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/app/_route/ingredients/add': {
      id: '/app/_route/ingredients/add'
      path: '/add'
      fullPath: '/app/ingredients/add'
      preLoaderRoute: typeof AppRouteIngredientsAddImport
      parentRoute: typeof AppRouteIngredientsImport
    }
    '/app/_route/recipes/add': {
      id: '/app/_route/recipes/add'
      path: '/add'
      fullPath: '/app/recipes/add'
      preLoaderRoute: typeof AppRouteRecipesAddImport
      parentRoute: typeof AppRouteRecipesImport
    }
    '/app/_route/ingredients/edit/$id': {
      id: '/app/_route/ingredients/edit/$id'
      path: '/edit/$id'
      fullPath: '/app/ingredients/edit/$id'
      preLoaderRoute: typeof AppRouteIngredientsEditIdImport
      parentRoute: typeof AppRouteIngredientsImport
    }
    '/app/_route/recipes/edit/$id': {
      id: '/app/_route/recipes/edit/$id'
      path: '/edit/$id'
      fullPath: '/app/recipes/edit/$id'
      preLoaderRoute: typeof AppRouteRecipesEditIdImport
      parentRoute: typeof AppRouteRecipesImport
    }
    '/app/_route/recipes/preview/$id': {
      id: '/app/_route/recipes/preview/$id'
      path: '/preview/$id'
      fullPath: '/app/recipes/preview/$id'
      preLoaderRoute: typeof AppRouteRecipesPreviewIdImport
      parentRoute: typeof AppRouteRecipesImport
    }
  }
}

// Create and export the route tree

interface AppRouteIngredientsRouteChildren {
  AppRouteIngredientsAddRoute: typeof AppRouteIngredientsAddRoute
  AppRouteIngredientsEditIdRoute: typeof AppRouteIngredientsEditIdRoute
}

const AppRouteIngredientsRouteChildren: AppRouteIngredientsRouteChildren = {
  AppRouteIngredientsAddRoute: AppRouteIngredientsAddRoute,
  AppRouteIngredientsEditIdRoute: AppRouteIngredientsEditIdRoute,
}

const AppRouteIngredientsRouteWithChildren =
  AppRouteIngredientsRoute._addFileChildren(AppRouteIngredientsRouteChildren)

interface AppRouteRecipesRouteChildren {
  AppRouteRecipesAddRoute: typeof AppRouteRecipesAddRoute
  AppRouteRecipesEditIdRoute: typeof AppRouteRecipesEditIdRoute
  AppRouteRecipesPreviewIdRoute: typeof AppRouteRecipesPreviewIdRoute
}

const AppRouteRecipesRouteChildren: AppRouteRecipesRouteChildren = {
  AppRouteRecipesAddRoute: AppRouteRecipesAddRoute,
  AppRouteRecipesEditIdRoute: AppRouteRecipesEditIdRoute,
  AppRouteRecipesPreviewIdRoute: AppRouteRecipesPreviewIdRoute,
}

const AppRouteRecipesRouteWithChildren = AppRouteRecipesRoute._addFileChildren(
  AppRouteRecipesRouteChildren,
)

interface AppRouteRouteChildren {
  AppRouteIngredientsRoute: typeof AppRouteIngredientsRouteWithChildren
  AppRouteRecipesRoute: typeof AppRouteRecipesRouteWithChildren
  AppRouteShoppingRoute: typeof AppRouteShoppingRoute
  AppRouteIndexRoute: typeof AppRouteIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppRouteIngredientsRoute: AppRouteIngredientsRouteWithChildren,
  AppRouteRecipesRoute: AppRouteRecipesRouteWithChildren,
  AppRouteShoppingRoute: AppRouteShoppingRoute,
  AppRouteIndexRoute: AppRouteIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AppRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/ingredients': typeof AppRouteIngredientsRouteWithChildren
  '/app/recipes': typeof AppRouteRecipesRouteWithChildren
  '/app/shopping': typeof AppRouteShoppingRoute
  '/app/': typeof AppRouteIndexRoute
  '/app/ingredients/add': typeof AppRouteIngredientsAddRoute
  '/app/recipes/add': typeof AppRouteRecipesAddRoute
  '/app/ingredients/edit/$id': typeof AppRouteIngredientsEditIdRoute
  '/app/recipes/edit/$id': typeof AppRouteRecipesEditIdRoute
  '/app/recipes/preview/$id': typeof AppRouteRecipesPreviewIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/app': typeof AppRouteIndexRoute
  '/app/ingredients': typeof AppRouteIngredientsRouteWithChildren
  '/app/recipes': typeof AppRouteRecipesRouteWithChildren
  '/app/shopping': typeof AppRouteShoppingRoute
  '/app/ingredients/add': typeof AppRouteIngredientsAddRoute
  '/app/recipes/add': typeof AppRouteRecipesAddRoute
  '/app/ingredients/edit/$id': typeof AppRouteIngredientsEditIdRoute
  '/app/recipes/edit/$id': typeof AppRouteRecipesEditIdRoute
  '/app/recipes/preview/$id': typeof AppRouteRecipesPreviewIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/app': typeof AppRouteWithChildren
  '/app/_route': typeof AppRouteRouteWithChildren
  '/app/_route/ingredients': typeof AppRouteIngredientsRouteWithChildren
  '/app/_route/recipes': typeof AppRouteRecipesRouteWithChildren
  '/app/_route/shopping': typeof AppRouteShoppingRoute
  '/app/_route/': typeof AppRouteIndexRoute
  '/app/_route/ingredients/add': typeof AppRouteIngredientsAddRoute
  '/app/_route/recipes/add': typeof AppRouteRecipesAddRoute
  '/app/_route/ingredients/edit/$id': typeof AppRouteIngredientsEditIdRoute
  '/app/_route/recipes/edit/$id': typeof AppRouteRecipesEditIdRoute
  '/app/_route/recipes/preview/$id': typeof AppRouteRecipesPreviewIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/app'
    | '/app/ingredients'
    | '/app/recipes'
    | '/app/shopping'
    | '/app/'
    | '/app/ingredients/add'
    | '/app/recipes/add'
    | '/app/ingredients/edit/$id'
    | '/app/recipes/edit/$id'
    | '/app/recipes/preview/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/app'
    | '/app/ingredients'
    | '/app/recipes'
    | '/app/shopping'
    | '/app/ingredients/add'
    | '/app/recipes/add'
    | '/app/ingredients/edit/$id'
    | '/app/recipes/edit/$id'
    | '/app/recipes/preview/$id'
  id:
    | '__root__'
    | '/'
    | '/signin'
    | '/signup'
    | '/app'
    | '/app/_route'
    | '/app/_route/ingredients'
    | '/app/_route/recipes'
    | '/app/_route/shopping'
    | '/app/_route/'
    | '/app/_route/ingredients/add'
    | '/app/_route/recipes/add'
    | '/app/_route/ingredients/edit/$id'
    | '/app/_route/recipes/edit/$id'
    | '/app/_route/recipes/preview/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  AppRoute: typeof AppRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  AppRoute: AppRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/signin",
        "/signup",
        "/app"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/signin": {
      "filePath": "signin.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/app": {
      "filePath": "app",
      "children": [
        "/app/_route"
      ]
    },
    "/app/_route": {
      "filePath": "app/_route.tsx",
      "parent": "/app",
      "children": [
        "/app/_route/ingredients",
        "/app/_route/recipes",
        "/app/_route/shopping",
        "/app/_route/"
      ]
    },
    "/app/_route/ingredients": {
      "filePath": "app/_route.ingredients.tsx",
      "parent": "/app/_route",
      "children": [
        "/app/_route/ingredients/add",
        "/app/_route/ingredients/edit/$id"
      ]
    },
    "/app/_route/recipes": {
      "filePath": "app/_route.recipes.tsx",
      "parent": "/app/_route",
      "children": [
        "/app/_route/recipes/add",
        "/app/_route/recipes/edit/$id",
        "/app/_route/recipes/preview/$id"
      ]
    },
    "/app/_route/shopping": {
      "filePath": "app/_route.shopping.tsx",
      "parent": "/app/_route"
    },
    "/app/_route/": {
      "filePath": "app/_route.index.tsx",
      "parent": "/app/_route"
    },
    "/app/_route/ingredients/add": {
      "filePath": "app/_route.ingredients.add.tsx",
      "parent": "/app/_route/ingredients"
    },
    "/app/_route/recipes/add": {
      "filePath": "app/_route.recipes.add.tsx",
      "parent": "/app/_route/recipes"
    },
    "/app/_route/ingredients/edit/$id": {
      "filePath": "app/_route.ingredients.edit.$id.tsx",
      "parent": "/app/_route/ingredients"
    },
    "/app/_route/recipes/edit/$id": {
      "filePath": "app/_route.recipes.edit.$id.tsx",
      "parent": "/app/_route/recipes"
    },
    "/app/_route/recipes/preview/$id": {
      "filePath": "app/_route.recipes.preview.$id.tsx",
      "parent": "/app/_route/recipes"
    }
  }
}
ROUTE_MANIFEST_END */
